apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-wildcard
  namespace: sandbox
spec:
  secretName: istio-wildcard
  dnsNames:
  - "*.skrzypek.dev"
  issuerRef:
    name: istio-issuer
    kind: Issuer
    group: cert-manager.io
